### PR TITLE
fix template compiler error

### PR DESCRIPTION
**Pull request by bichikim**
add using render() function

### CODE REVIEW

**Comment by taoeffect** [comment]
Hmm... so this works? I'll need to verify it on my end but if you got it to work that's awesome! (And in which case I'll probably request that the comment be updated as well)

**Comment by bichikim** [comment]
@taoeffect it works in my tests :)

**Comment by taoeffect** [comment]
OK, verified that it works, I'll fix up the comments etc. Thanks!

**Comment by taoeffect** [comment]
2.0.2 released :)

**Pull request merged**
